// Bygninger og anlegg
=== Innledning
Aktuell kilde for grupperingen bygninger og anlegg i N10 Beredskap er i de fleste tilfeller FKB-datasett. Supplering fra andre datasett i form av f.eks. POI-er for uttegning av symboler er aktuelt.



=== Kilder

* *FKB-Arealbruk* +

* *FKB-Bygning* +
Omrissgeometri hentes fra FKB-Bygning. 

* *FKB-BygnAnlegg* +
De fleste objekttyper som brukes i N10 Beredskap kommer fra dette FKB-datasettet.
Objekttype Navigasjonsinstallasjon fra FKB-datasettet brukes ikke. 

* *FKB-Ledning* +
Bruk av data fra FKB-Ledning er beskrevet i eget kapittel.

* *FKB-Vann* +
Kun et fåtall objekttyper hentes fra dette datasettet.

* *FKB-Veg* +
Kun et fåtall objekttyper hentes fra dette datasettet.

* *N50K* +
Henter ut Lysløype, Sykehus, Turisthytte, Hoppbakke, Pir, Molo, SpesiellDetalj, Flytebrygge, Campingplass, Parkeringsområde og Reingjerde. Henter fra N50, når objektet ikke eksisterer som geometritype i FKB eller at objekttypen ikke eksisterer i FKB.

I FKB er registrering av enkelte objekttyper opsjonelt, det kan gjelde for alle eller noen av områdestandardene (A, B, C eller D). Dette kan føre til at N10B-datasettet ikke blir homogent over større områder. For eksempel er registrering av objekttype Parkeringsområde i FKB-Veg opsjonelt i alle områdestandardene.


=== Tilleggsbetingelser

En av utfordringene ved buk av FKB-data som kilde er få til god håndtering av alle tilleggsbetingelser av ulike typer som er beskrevet i datamodellen. Det gjelder varianter av geometribegrensninger for lengde, areal, høyde, øyer i flategeometri samt omgjøring av geometrirepresentasjon. I tillegg må man vurdere egne bortvalgsmekanismer innenfor enkelte geografiske områder, f.eks. innenfor områder definert som by/tettsted.

Objekter som har stor utstrekning kan være registrert på ulike tidspunkt, med ulike målemetoder og/eller i ulike prosjekter. Dette fører til behov for å slå sammen objektforekomster før vurdering mot andre kriterier som f.eks. minimumslengde.
Dersom sammenslåing droppes vil konsekvensen bli at mange enkeltforekomster som geometrisk henger sammen ikke oppfyller tileeggsbetingelser og dermed ikke blir med over i avledet datasett. 

Produktspesifikasjonen sier ingen ting om siling/tynning av geometri.

=== Resultatvurdering

De gitte verdiene for diverse tilleggskriterier fører til at objektforeomstene fra FKB beholder en stor detaljeringsgrad.

Noen forekomster forekommer i betydelig grad i flere nivåer vertikalt, f.eks. er det ofte gjerde på toppen av en mur.

Opprinnelig FKB-geometri beholdes. Det fører til at langs samferdelsinfrastruktur som f.eks. jernbane vil gjerder og samferdselsgeometrien ligg svært tett. 

I innledende testing er følgende N10B-objekttyper hentet fra FKB-data:

.N10B-objekttyper fra FKB-data
[width="50%",options="header"]
|====================
|  Objekttypenavn
|  Bygning
|  Demning
|  Gjerde
|  Grunnmur
|  Mur
|  Oppdrettslokalitet
|  Parkeringsområde
|  Pipe
|  Ruin
|  Skjerm
|  Slipp
|  Svømmebasseng
|  Takoverbygg
|  Taubane
|  Tribune
|  Vindturbin
|  Voll
|====================

=== Forslag til endring i Produktspesifikasjonen

Det er vurdert slik at kriteriene for N10 Beredskap, spesielt anleggslinjer er noe unøyaktige og trenger å spesifiseres. Det er i første versjon lagt til ett forslag for å kunne gi ett bedre kartografisk presentasjon.

Forslag til kriterie:
Anleggslinjer untatt Flateavgrensning, Slipp og Taubane skal ikke ligge i tettbebyggelse eller bymessigbebyggelse samt ikke ligge nærmere 20 meter fra vei eller bane. 
Anleggslinjer skal ikke overlappe hverandre og vil prioriteres i denne rekkefølgen:

Flateavgrensning
Flytebrygge
Taubane
Hoppbakke
Idrettsanlegg
Lysløype
Skytebaneinnretning
Rørgate
SpesillDetalj
Pir
Voll
Skjerm
Mur
Gjerde
Grunnmur
Ruin

Videre er anbefalingen at slipp heller blir en del av point of interest, siden denne informasjonen er umulig å lese/forstås i ett kart. I Kode, ligger forslaget på hvordan denne generaliseringen kan gjøres.

=== Kode

Omkodinger og testing er utført v.h.a. FYSAK-makroer med Python-overbygning.

Makroene er det viktigste, Python-koden er hovedsaklig brukt til å administrere dataflyt.

==== Forslag til endring i kriterie Anleggslinje:

include::Kode/Forslag_endring_kriterier_anleggslinje.adoc[]
