:datasett: Topografisk grunndatabase 
:kortnavn: TopografiskGrunndatabase 
:versjon: 1.0 
:skjemaversjon: 1.0 
:publisert: 2024-02-06
:underversjon: 2024-02-01 
:metadata-url: Link_til_Geonorge
:prodspek-forrige:
:versjon-forrige: 
:bilde_sti: https://github.com/kartverket/topografisk-grunndatabase-produktspesifikasjon/tree/main/figurer

include::../kapittel/filhode.adoc[]


== Innledning, historikk og endringslogg

=== Innledning
Topografisk grunndatabase (TG) er en DLM. Topografisk grunndatabase er en landsdekkende homogen kartdatabase. Kartdataene skal være i målestokken 1:10 000 og danne grunnlaget for kartplott i 1:20 000. 

=== Historikk
Arbeidet med å spesifisere TG startet 2023. Datasettet skulle dekke behovet for en landsdekkende, homogen kartdatabase i stor målestokk. Arbeidet med første produktspesifikasjon var ett samarbeid mellom flere fagfelt; FKB, Kartprodukter, Datadelingsteamet, Standardisering og Sjø.

|===
|Versjon|Dato |Utførtav |Merknad
|0.1|X|Ida Hope Barth, Mika Sundin, Nils Ivar Nes, Tore Freddy Bæk, Mathilde Skjæveland Skår og Åsmund Tjora|Utkast
|===


=== Endringslogg

== Definisjoner og forkortelser

=== Definisjoner

include::../kapittel/definisjoner.adoc[]

=== Forkortelser

include::../kapittel/forkortelser.adoc[]

<<<

== Generelt om spesifikasjonen

=== Unik identifisering


////
Identisk med tag 'SOSI_kortnavn' på pakka i EA.

Er case-sensitiv i SOSI-kontroll.

Norske tegn er ok hvis enkoding er riktig innstilt. Kontakt standardiseringssekretariatet hvis du har problemer med norske tegn.
////
==== Kortnavn
{kortnavn}

==== Fullstendig navn
{datasett} 

// Identisk med tag på pakka i EA for SOSI_langnavn.

==== Versjon
{versjon}


// Identisk med tag på pakka i EA for version.

=== Referansedato
år-mnd-dag



// PSS og PSV er litt uklare på hva referansedato er. Det er nevnt gyldighetsdato og utgivelsesdato.

=== Ansvarlig organisasjon
Kartverket, Landdivisjonen, Avdeling for kartprodukter + 
Postadresse: 3507 Hønefoss + 
Besøksadresse: Kartverksveien 21, 3511 Hønefoss + 
E-post: post@kartverket.no + 
Telefon: 32 11 80 00 + 
Internettadresse: www.kartverket.no + 

=== Språk
Norsk

=== Hovedtema
Basis geodata

// Fritekst som beskriver hovedtema. Gjerne inspirert av DOK-hovedkategorier eller nasjonal temainndeling: 
// https://register.geonorge.no/subregister/metadata-kodelister/kartverket/nasjonal-temainndeling


=== Temakategori
Administrative grenser +
Helse +
Høydedata +
Innsjø og vassdrag +
Konstruksjoner +
Kyst og sjø +
Landbruk og havbruk +
Ledningsinformasjon +
Stedsangivelse +
Transport

// Temakategorier er en kodeliste i NS-ISO 19115. Hvis du ikke har tilgang til 19115, finner du en tabell i PSS avsnitt 13.5.2. Det angis én eller flere av kodene i tabellen for temakategorier.

=== Sammendrag
Topografisk grunndatabase skal dekke behovet for landsdekkende kartdata i stor målestokk. Hovedfokus er å danne ett grunnlag for kartdata, kartproduksjon og tilpasse databasen slik at den kan brukes for automatisk generalisering til mindre målestokker. 


////
PSV har gjemt dette punktet i 4.Kap 3.5/3.6/3.7.

Note: NS-ISO 19131 har som utgangspunkt at en produktspesifikasjon er en bestilling av en (framtidig) geodataleveranse, men det nevnes også at produktspesifikasjoner kan dokumentere eksisterende geodata (noe som er vanlig i Norge).

Brukstilfeller:
Som regel er det behov for dokumentasjon av brukstilfeller som et produkt er tenkt for. En oversiktlig liste med navnene til relevante brukstilfeller kan plasseres under formålskapittelet. Flere detaljer for de nevnte brukstilfellene kan samles i et vedlegg. 
 
I PSS nevnes ikke brukstilfeller, men det er naturlig å plassere de her. En framtidig versjon av ISO 19131 vil ta høyde for det og gi standardiserte føringer for hvor og hvordan brukstilfeller skal dokumenteres.
////

=== Formål

include::../kapittel/kap3.8_formal.adoc[]

include::../kapittel/kap3.9_representasjon.adoc[]

=== Supplerende beskrivelse
Data ikke angitt

<<<

== Spesifikasjonsomfang

include::../kapittel/kap4_omfang.adoc[]  

<<<

== Innhold og struktur

=== Omfang
<<HeleDatasettet,Hele datasettet>>

include::../produktspesifikasjon/kap5.adoc[] 

<<<
== Referansesystem

include::../kapittel/kap6_referansesystem.adoc[]


<<<

== Kvalitet

include::../kapittel/kap7_kvalitet.adoc[]


<<<

== Datafangst

include::../kapittel/kap8_datafangst.adoc[]

<<<


== Datavedlikehold

include::../kapittel/kap9_vedlikehold.adoc[]

<<<

<<<

== Presentasjon

=== Omfang
<<HeleDatasettet,Hele datasettet>>

=== Referanse til presentasjonskatalog
Spesifikasjon for skjermkartografi er et hjelpemiddel til å oppnå en god skjermpresentasjon av kartdata fra Kartverket og Geovekst. Spesifikasjonen er tilpasset produktene N50-N5000 Kartdata og FKB-data. Den gir en grafisk fremstilling av kartobjektene vist i ulike målestokkintervaller.
Spesifikasjonen er utviklet av Kartverket og Forsvaret, og kan benyttes fritt av alle som ønsker det. 

Det eksisterer ikke i dag en egen skjermkartografi eller tegneregler for topografisk grunndatabase.

<<<

== Leveranse

include::../kapittel/kap11_leveranse.adoc[]

<<<

== Tilleggsinformasjon
Ingen angitt informasjon

== Metadata


include::../kapittel/kap13_metadata.adoc[]

<<<

[appendix]
== GML-realisering

GML-realiseringen følger kravene i "Realisering i GML-format 5.0" <<SOSI-GML>>. Realiseringen defineres av følgende filer:


[appendix]
== SOSI-format-realisering

SOSI-realiseringen følger kravene i "Realisering i SOSI-format 5.0" <<SOSI-FORMAT>>. Under en utlisting av SOSI-formatrealiseringen:

include::../kapittel/SOSI_format_realisering.adoc[]

[appendix]
== Normative referanser

include::../kapittel/normativ_ref.adoc[]

:sectnums!:

<<<




