

=== Omfang
<<HeleDatasettet,Hele datasettet>>

=== Beskrivelse av datakvalitet
FKB er detaljerte kartdata med en nøyaktighet på typisk 10 cm - 1 m og kan egne seg som datagrunnlag  i f.eks. beredskap, analyse, planlegging og prosjektering i tillegg til å fungere som et topografisk grunnkart. 

Den dominerende datafangstmetoden for FKB-data er fotogrammetrisk registrering. For fotogrammetrisk registrering er det angitt detaljerte kvalitetskrav. Se {reginstr-url}[fotogrammetrisk registreringsinstruks for {fkbdatasett}].

FKB vil ofte også inneholde data fra andre datakilder, for eksempel data etablert gjennom kommunal/offentlig saksbehandling, innmelding fra publikum eller digitalisert fra ortofoto. Se kapittel 9 for en nærmere beskrivelse av datakilder ved vedlikehold av FKB-data. 

Prinsippet er at fullstendighet prioriteres foran nøyaktighet og FKB-data for et område vil derfor bestå av data med varierende grad av kvalitet. Alle data er kodet med datafangstdato og posisjonskvalitet slik at det er mulig å vurdere datakvaliteten til det enkelte dataobjekt. Det vil også være mulig å aggregere denne informasjonen som finnes på objektnivå opp til en beskrivelse av kvaliteten på datainnholdet i området som helhet. Det er imidlertid vanskelig å garantere datakvaliteten for FKB innenfor et område.

////
Dette kan være et vanskelig kapittel. Det første du bør gjøre er å sjekke hva du anførte som formål i avsnitt 3.8. Hvis du skal bestille data, er det mest naturlig om du her angir kvalitetskrav. Hvis du dokumenterer eksisterende geodata, derimot, bør kvaliteten her beskrive geodataene.

PSS kapittel 17 gir en innføring i kvalitet. Ofte innebærer kvalitet en statistisk analyse av kontrollmålinger av geodata. Hvis dette er helt ukjent for deg, kan du kanskje anføre at geodataene ikke er kontrollert.

Kvalitet kan også angis kvalitativt (noe NS-ISO 19115 og andre også omfatter). Det kan for eksempel være at geodataene er registrert etter en innmålingsinstruks, eller at de er resultat av beregninger beskrevet i en teknisk rapport eller vitenskapelig artikkel. Merk at dette er nært knyttet til kapittel 8.

Kvalitet skal også referere til omfang (scopes) angitt i kapittel 4. I tillegg kan du innenfor kvalitet også spesifisere enkelte deler (også scope), og angi ulike kvaliteter. Merk at norske geodata (SOSI-standarden) har mulighet for kvalitetsangivelse på objekttypene, men slike hører eventuelt hjemme i kapittel 5.

Hvis du (eller din organisasjon) ikke har peiling på kvaliteten til geodataene, er dette nyttig kvalitetsinformasjon som bør nevnes.

Kvalitetsinformasjon skal oppgis for hver av de fem kvalitetselementene som er oppgitt i PSV:
•	Fullstendighet
•	Stedfestingsnøyaktighet
•	Egenskapsnøyaktighet
•	Tidfestingsnøyaktighet
•	Logisk konsistens
Dersom det for et kvalitetselement ikke er mulig å angi noen fornuftig informasjon skal dette oppgis sammen med en forklaring på årsaken.
////