
=== Vedlikeholdsinformasjon Kartleggingsprosjekter

==== Omfang 
<<HeleDatasettet,Hele datasettet>>

==== Vedlikeholdsfrekvens 
 

Det er et ønske om å ha oppdaterte data, men vedlikeholdsfrekvens for kartleggingsprosjekter er ikke angitt. 

==== Vedlikeholdsbeskrivelse 
På nåværende tidspunkt er det vanskelig å si hva som skal ajourføres lokalt i Topografisk grunndatabase og hva som skal hentes fra andre geodatakilder. Det som skal ajourføres direkte i basen er avhengig av datafangstmetode.




=== Vedlikeholdsinformasjon Kontinuerlig ajourhold

==== Omfang
<<HeleDatasettet,Hele datasettet>>

==== Vedlikeholdsfrekvens
kontinuerlig

==== Vedlikeholdsbeskrivelse
På nåværende tidspunkt er det vanskelig å si hva som skal ajourføres lokalt i Topografisk grunndatabase og hva som skal hentes fra andre geodatakilder. Kartdata hentet fra andre datakilder vil være sentralt i det kontinuerlige vedlikeholdet. Oppdatering og ajourhold vil kunne basere seg på endringsanalyser.

=== Vedlikeholdsinformasjon Meldinger om feil og mangler

==== Omfang
<<HeleDatasettet,Hele datasettet>>

==== Vedlikeholdsfrekvens
Kontinuerlig

==== Vedlikeholdsbeskrivelse
Kartverket mottar gjennom kundesenteret og tjenesten Rettikartet.no en del meldinger om feil og mangler i i kartet fra publikum. Disse meldingene kan etter en vurdering mot andre datakilder bli lagt inn i Topografisk grunndatabase.

