
== Kvalitet

////
Dette kan være et vanskelig kapittel. Det første du bør gjøre er å sjekke hva du anførte som formål i avsnitt 3.8. Hvis du skal bestille data, er det mest naturlig om du her angir kvalitetskrav. Hvis du dokumenterer eksisterende geodata, derimot, bør kvaliteten her beskrive geodataene.

PSS kapittel 17 gir en innføring i kvalitet. Ofte innebærer kvalitet en statistisk analyse av kontrollmålinger av geodata. Hvis dette er helt ukjent for deg, kan du kanskje anføre at geodataene ikke er kontrollert.

Kvalitet kan også angis kvalitativt (noe NS-ISO 19115 og andre også omfatter). Det kan for eksempel være at geodataene er registrert etter en innmålingsinstruks, eller at de er resultat av beregninger beskrevet i en teknisk rapport eller vitenskapelig artikkel. Merk at dette er nært knyttet til kapittel 8.

Kvalitet skal også referere til omfang (scopes) angitt i kapittel 4. I tillegg kan du innenfor kvalitet også spesifisere enkelte deler (også scope), og angi ulike kvaliteter. Merk at norske geodata (SOSI-standarden) har mulighet for kvalitetsangivelse på objekttypene, men slike hører eventuelt hjemme i kapittel 5.

Hvis du (eller din organisasjon) ikke har peiling på kvaliteten til geodataene, er dette nyttig kvalitetsinformasjon som bør nevnes.

Kvalitetsinformasjon skal oppgis for hver av de fem kvalitetselementene som er oppgitt i PSV:
•	Fullstendighet
•	Stedfestingsnøyaktighet
•	Egenskapsnøyaktighet
•	Tidfestingsnøyaktighet
•	Logisk konsistens
Dersom det for et kvalitetselement ikke er mulig å angi noen fornuftig informasjon skal dette oppgis sammen med en forklaring på årsaken.
////