
=== Romlig referansesystem 1

==== Omfang
<<HeleDatasettet,Hele datasettet>>

==== Navn på kilden til referansesystemet
Norwegian Mapping Authority

==== Ansvarlig organisasjon for referansesystemet
The international Association of Oil & Gas Producers

==== Link til mer informasjon om referansesystemet
http://www.espg.org +
https://register.geonorge.no/epsg-koder

==== Koderom
EPSG

==== Identifikasjonskode
EPSG 5972

==== Kodeversjon
2020-03-30

=== Romlig referansesystem 2

==== Omfang
<<HeleDatasettet,Hele datasettet>>

==== Navn på kilden til referansesystemet
Norwegian Mapping Authority

==== Ansvarlig organisasjon for referansesystemet
The international Association of Oil & Gas Producers

==== Link til mer informasjon om referansesystemet
http://www.espg.org +
https://register.geonorge.no/epsg-koder

==== Koderom
EPSG

==== Identifikasjonskode
EPSG 5973

==== Kodeversjon
2020-03-30

=== Romlig referansesystem 3

==== Omfang
<<HeleDatasettet,Hele datasettet>>

==== Navn på kilden til referansesystemet
Norwegian Mapping Authority

==== Ansvarlig organisasjon for referansesystemet
The international Association of Oil & Gas Producers

==== Link til mer informasjon om referansesystemet
http://www.espg.org +
https://register.geonorge.no/epsg-koder

==== Koderom
EPSG

==== Identifikasjonskode
EPSG 5975

==== Kodeversjon
2020-03-30


=== Temporalt referansesystem


==== Navn på temporalt referansesystem
UTC

Dersom ikke tidssone er spesielt angitt ved angivelse av tidspunkt skal man anta at det er norsk tid som benyttes. Dvs. UTC+1 (normaltid) på vinteren og UTC+2 (sommertid) på sommeren.

==== Omfang
<<HeleDatasettet,Hele datasettet>>