
=== Vedlikeholdsinformasjon Kartleggingsprosjekter

==== Omfang 
<<HeleDatasettet,Hele datasettet>>

==== Vedlikeholdsfrekvens 
 

Det er et ønske om å ha oppdaterte data, men vedlikeholdsfrekvens for kartleggingsprosjekter er ikke angitt. 

==== Vedlikeholdsbeskrivelse 
På nåværende tidspunkt er det vanskelig å si om det er nødvedig å ajourføre lokalt i N10 Beredskap, men målet er å ha automatiske generaliseringsløyper for å oppdatere N10 Beredskap.




=== Vedlikeholdsinformasjon Kontinuerlig ajourhold

==== Omfang
<<HeleDatasettet,Hele datasettet>>

==== Vedlikeholdsfrekvens
kontinuerlig

==== Vedlikeholdsbeskrivelse
På nåværende tidspunkt er det vanskelig å si om det er nødvedig å ajourføre lokalt i N10 Beredskap, men målet er å ha automatiske generaliseringsløyper for å oppdatere N10 Beredskap.

=== Vedlikeholdsinformasjon Meldinger om feil og mangler

==== Omfang
<<HeleDatasettet,Hele datasettet>>

==== Vedlikeholdsfrekvens
Kontinuerlig

==== Vedlikeholdsbeskrivelse
Kartverket mottar gjennom kundesenteret og tjenesten Rettikartet.no en del meldinger om feil og mangler i i kartet fra publikum. Disse meldingene skal sendes til primærdataeier og endres der, før Topografisk grunndatabase oppdateres og N10 Beredskap kan hente inn data etter rettelse.

